### ISSUE TITLE
Does not recognize livewire component methods

### ISSUE THREAD

**Issue by nucarlos** [livewire-ui/modal#8]
I have component Seach according to documentation

This is the component view:
`<button wire:click="update()" type="button"> Update </button>`

This is a component code:

```
<?php

namespace App\Http\Livewire;

use Illuminate\Support\Str;
use LivewireUI\Modal\ModalComponent;
use Livewire\WithPagination;
use App\Models\Persona;

class Search extends ModalComponent
{
    use WithPagination;
    public $searchTerm;

    public function render()
    {
        $searchTerm = '%' . Str::upper($this->searchTerm) .'%';
        return view('livewire.search', [
            'personas' => Persona::where('nombre','like', $searchTerm)->paginate(15)
        ]);
    }

    public function update()
    {
        // Todo 
        $this->closeModal();
    }
}
```

This is a error:
`Unable to call component method. Public method [update] not found on component: [livewire-u-i.modal.modal]`

**Comment by PhiloNL** [comment]
@nucarlos hmm, that should work. It seems like it's trying to call the `update` method on the modal component instead of the `Search` component. Could you post the entire `livewire.search` file?

Also, did you make any custom changes to the modal component itself?

**Comment by nucarlos** [comment]
Thank you for your support

The livewire.search file is complete

I just wanted to test that it works when I invoke the update method, and then add my code

**Comment by nucarlos** [comment]
do not make any changes to the modal component

**Comment by PhiloNL** [comment]
Sorry, I don't follow. Is the issue resolved? If it isn't could you please post the code of your entire component (the class and the blade file). Thanks!

**Comment by PhiloNL** [comment]
Closing this issue, let me know if this is still a problem.

**Comment by vincentkosciuszko** [comment]
Still not working, two issues were created and you closed both without giving any informations.

**Comment by PhiloNL** [comment]
@vincentkosciuszko that's because I don't have enough information as I mentioned earlier. If you create a repository with a fresh installation of Laravel, Livewire, Livewire UI Modal, replicate the issue, and share this repository with me, I can take a look.

**Comment by vincentkosciuszko** [comment]
Well you said it yourself, it try to call the function on the modal instead of the search component in this case. That's exactly the same issue I have.

**Comment by denbnddb** [comment]
Today I met the same error when trying to use 'wire-elements/modal'. But in my case the problem was solved. I'm not sure if this issue is the same as my case, but I'll write it for reference.

I did as the documentation [https://philo.dev/laravel-modals-with-livewire/], but I got an error in the `$ formAction` part.
When I press the Start Counting button, I get the error `Unable to call component method. Public method [update] not found on component: [livewire-u-i.modal.modal]`.

The cause was that I had a comment at the beginning of hello-world.blade.php, like this.

\<!--
\<div\>
    Hello World
<\/div\>
--\>
\<x-modal formAction="update"\>
 ;

Thank you for the wonderful library.

**Comment by arwanfiles** [comment]
> Today I met the same error when trying to use 'wire-elements/modal'. But in my case the problem was solved. I'm not sure if this issue is the same as my case, but I'll write it for reference.
> 
> I did as the documentation [https://philo.dev/laravel-modals-with-livewire/], but I got an error in the `$ formAction` part. When I press the Start Counting button, I get the error `Unable to call component method. Public method [update] not found on component: [livewire-u-i.modal.modal]`.
> 
> The cause was that I had a comment at the beginning of hello-world.blade.php, like this.
> 
>  <x-modal formAction="update"> ;
> 
> Thank you for the wonderful library.

same issue here..

**Comment by arwanfiles** [comment]
> Today I met the same error when trying to use 'wire-elements/modal'. But in my case the problem was solved. I'm not sure if this issue is the same as my case, but I'll write it for reference.
> 
> I did as the documentation [https://philo.dev/laravel-modals-with-livewire/], but I got an error in the `$ formAction` part. When I press the Start Counting button, I get the error `Unable to call component method. Public method [update] not found on component: [livewire-u-i.modal.modal]`.
> 
> The cause was that I had a comment at the beginning of hello-world.blade.php, like this.
> 
>  <x-modal formAction="update"> ;
> 
> Thank you for the wonderful library.

Same issue I met.
Solve by wrapping template file with `div` or othe html tag.

Not Working
```
<div class="modal-head">
    <h1>This is modal title</h1>
</div>

<div class="modal-body">
    <div>This is modal body message</div>
</div>

<div class="modal-footer">
    <button type="button" wire:click="method">Execute It</button>
</div>
```

It working now for me
```
<div>
    <div class="modal-head">
        <h1>This is modal title</h1>
    </div>

    <div class="modal-body">
        <div>This is modal body message</div>
    </div>

    <div class="modal-footer">
        <button type="button" wire:click="method">Execute It</button>
    </div>
</div>
```

Thanks for this awesome library.

**Comment by marcelooblan2016** [comment]
For people still experiencing (it may save you hours); 
Public method [{{yourMethod}}] not found on component: [livewire-u-i.modal.modal]
![image](https://user-images.githubusercontent.com/36547331/219922927-460c8d28-1b61-4261-843c-827d9fd41483.png)
![image](https://user-images.githubusercontent.com/36547331/219922958-579c750c-22b7-4837-b47d-544a4696bb26.png)

in you modal blade make sure it has no comment above, remove it. (i believe it has something to do with their parser).
![image](https://user-images.githubusercontent.com/36547331/219922997-8562ea0a-946d-4c3d-8017-1107a91ef0c0.png)
![image](https://user-images.githubusercontent.com/36547331/219923009-7406bb48-0c51-448f-81fa-041408fedaa9.png)

**Comment by MarcGaumont** [comment]
Just got this error too, for me it was having this :
![Screenshot 2023-10-13 at 12 29 44 PM](https://github.com/wire-elements/modal/assets/8861811/e64be82d-97cd-4b86-aca8-aa4af38508f3)

Solved by removing that code... oddly, it works fine on another page with it there, but not on another.
